const form = document.getElementById('form');
const output = document.getElementById('output_text');
const position = document.getElementById('position');
const addedCount = document.getElementById('added_count');
const autoFix = document.getElementById('auto_fix_263');

// Blocks already committed with “Add Another Command Block”.
const commandBlocks = [];

position.addEventListener('input', generate_output_command);
form.addEventListener('input', generate_output_command);

function minecraftId(id) {
    const clean = String(id).trim().replace(/^['"]|['"]$/g, '');
    return clean.includes(':') ? clean : `minecraft:${clean}`;
}

// Targeted fixer for the 26.3 syntax changes that commonly occur inside
// commands generated by older one-command-creation tools.
function fixCommandFor263(command) {
    let text = command;

    text = text.replace(/BlockState:\{Name:((?:\\"[^\"]*\\"|"[^"]*"|[A-Za-z0-9_.:+-]+))/g,
        (match, raw) => `BlockState:{id:"${minecraftId(raw.replaceAll('\\"', '"'))}"`);

    text = text.replace(/block_state:\{Name:((?:\\"[^\"]*\\"|"[^"]*"|[A-Za-z0-9_.:+-]+))/g,
        (match, raw) => `block_state:{id:"${minecraftId(raw.replaceAll('\\"', '"'))}"`);

    text = text.replace(/(BlockState:\{[^{}]*?),Properties:/g, '$1,properties:');
    text = text.replace(/(block_state:\{[^{}]*?),Properties:/g, '$1,properties:');

    // Inline predicates changed from "condition" to mandatory "type" in 26.3.
    text = text.replace(/"condition"\s*:/g, '"type":');

    return text;
}

function escapeSnbtString(value) {
    return String(value)
        .replaceAll('\\', '\\\\')
        .replaceAll('"', '\\"')
        .replaceAll('\r', '\\r')
        .replaceAll('\n', '\\n');
}

function readCurrentBlock() {
    const data = new FormData(form);

    const prefix = String(data.get('command_type') || '').trim().toLowerCase();
    const direction = String(data.get('direction') || 'up').trim().toLowerCase();
    const conditional = String(data.get('conditional') || 'false').trim().toLowerCase();
    const alwaysActive = Number(data.get('always_active') || 0);

    let command = String(data.get('command') || '').trim();
    if (autoFix && autoFix.checked) command = fixCommandFor263(command);

    return {
        blockId: `minecraft:${prefix}command_block`,
        direction,
        conditional,
        alwaysActive,
        command
    };
}

function blockStateSnbt(block) {
    return `BlockState:{id:"${block.blockId}",properties:{facing:"${block.direction}",conditional:"${block.conditional}"}}`;
}

function tileDataSnbt(block) {
    return `TileEntityData:{auto:${block.alwaysActive},Command:"${escapeSnbtString(block.command)}"}`;
}

// Build the passenger stack from the bottom up. The final falling_block is air,
// matching the original generator's cleanup behavior.
function buildPassengerTail(blocks) {
    let child = '{id:"minecraft:falling_block",BlockState:{id:"minecraft:air"}}';

    for (let i = blocks.length - 1; i >= 0; i--) {
        const block = blocks[i];
        child = `{id:"minecraft:falling_block",${blockStateSnbt(block)},${tileDataSnbt(block)},Passengers:[{id:"minecraft:armor_stand",Health:0f,Passengers:[${child}]}]}`;
    }

    return child;
}

function generate_output_command() {
    const current = readCurrentBlock();
    const allBlocks = [...commandBlocks, current];
    const summonPos = position.value.trim() || '~ ~ ~';

    // The first command block is the root falling_block. Every later command
    // block is nested below it using the same armor-stand passenger pattern.
    const first = allBlocks[0];
    const remaining = allBlocks.slice(1);

    let passengers;
    if (remaining.length > 0) {
        passengers = `Passengers:[{id:"minecraft:armor_stand",Health:0f,Passengers:[${buildPassengerTail(remaining)}]}]`;
    } else {
        passengers = 'Passengers:[{id:"minecraft:armor_stand",Health:0f,Passengers:[{id:"minecraft:falling_block",BlockState:{id:"minecraft:air"}}]}]';
    }

    output.value = `/summon minecraft:falling_block ${summonPos} {${blockStateSnbt(first)},${tileDataSnbt(first)},${passengers}}`;

    if (addedCount) {
        addedCount.textContent = `${commandBlocks.length} added + current block`;
    }
}

function add_command_block() {
    const current = readCurrentBlock();

    if (!current.command) {
        setStatus('Enter a command before adding another command block.', true);
        return;
    }

    commandBlocks.push(current);
    form.reset();
    // Preserve auto-fix as enabled after resetting the form.
    if (autoFix) autoFix.checked = true;
    setStatus(`Added command block #${commandBlocks.length}.`);
    generate_output_command();
}

function undo_command_block() {
    if (commandBlocks.length === 0) {
        setStatus('There are no added command blocks to undo.', true);
        return;
    }
    commandBlocks.pop();
    setStatus('Removed the last added command block.');
    generate_output_command();
}

function clear_all() {
    commandBlocks.length = 0;
    form.reset();
    position.value = '~ ~ ~';
    if (autoFix) autoFix.checked = true;
    setStatus('Cleared the generator.');
    generate_output_command();
}

async function copy_output() {
    if (!output.value) return;

    const button = document.getElementById('copy_output');
    const original = button.textContent;

    try {
        await navigator.clipboard.writeText(output.value);
    } catch (error) {
        output.focus();
        output.select();
        document.execCommand('copy');
    }

    button.textContent = 'Copied!';
    setTimeout(() => button.textContent = original, 1200);
}

function setStatus(message, error = false) {
    const el = document.getElementById('status');
    if (!el) return;
    el.textContent = message;
    el.classList.toggle('error', error);
}

// Expose functions used by HTML buttons.
window.add_command_block = add_command_block;
window.undo_command_block = undo_command_block;
window.clear_all = clear_all;
window.copy_output = copy_output;

position.value = position.value || '~ ~ ~';
generate_output_command();
